export type MembershipTier = "normal" | "silver" | "gold" | "super_gold";

export interface Product {
  id: number;
  name: string;
  slug: string;
  category: string;
  prices: Record<MembershipTier, number>;
  points: number;
  image: string;
  description: string;
  ingredients: string;
  usage: string;
  benefits: string;
  origin: string;
  manufacturer: string;
  distributor: string;
  registration: string;
  licenseImage?: string;
}

export interface CartItem {
  product: Product;
  membership: MembershipTier;
  quantity: number;
}

export const MEMBERSHIP_LABELS: Record<MembershipTier, string> = {
  normal: "Thường",
  silver: "Bạc",
  gold: "Vàng",
  super_gold: "Siêu Vàng",
};

export const CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "thuc-pham-bo-sung", label: "Thực phẩm bổ sung" },
  { key: "bao-ve-suc-khoe", label: "Bảo vệ sức khỏe" },
  { key: "cham-soc-ca-nhan", label: "Chăm sóc cá nhân" },
  { key: "cham-soc-da", label: "Chăm sóc da (Orico)" },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Kem đánh răng VSmile",
    slug: "kem-danh-rang-vsmile",
    category: "cham-soc-ca-nhan",
    prices: { normal: 897000, silver: 780000, gold: 780000, super_gold: 702000 },
    points: 310,
    image: "/images/products/kem-danh-rang.jpg",
    description: "Kem đánh răng VSmile 150g/hộp - 5 hộp/lốc. Sản phẩm chăm sóc răng miệng cao cấp từ Vinalink.",
    ingredients: "Nuoc tinh khiet, Sorbitol, Silica hydrat hoa, Xylitol, Glycerin, Propylene glycol, Sodium chloride, Sodium lauryl sulfate, Sodium carboxymethylcellulose, Menthol, Canxi nano (Calcium Hydroxyapatite), Chiet xuat Neem (Azadirachta indica), Sodium saccharin, Lumbrokinase, huong lieu.",
    usage: "Nen dung sau khi ngu day, sau khi an va truoc khi di ngu, it nhat 2 lan/ngay.",
    benefits: "Giup rang trang sang, ngan ngua sau rang, bao ve nuou, thom mieng lau. Chua Canxi nano giup tai khoang rang, Lumbrokinase ho tro suc khoe nuou.",
  },
  {
    id: 2,
    name: "Cà phê Link",
    slug: "caphelink",
    category: "thuc-pham-bo-sung",
    prices: { normal: 888691, silver: 765818, gold: 765818, super_gold: 689237 },
    points: 300,
    image: "/images/products/caphelink.jpg",
    description: "Thực phẩm bổ sung Caphelink New 20g/hộp. Cà phê kết hợp các thành phần tốt cho sức khỏe.",
    ingredients: "Moi goi 16g: Duong tinh luyen, lactose, dextrose, manitol, bot kem khong sua, ca phe hoa tan nguyen chat, La chay (Artocarpus tonkinensis), Hoang ky (Astragalus membranaceus), DeltaImmune (vach te bao Lactobacillus rhamnosus) 150mg, Selen (tu men giau selen) 15mcg, huong ca phe, silicon dioxide, natri clorid.",
    usage: "Pha 1 gói với 150ml nước nóng, khuấy đều và thưởng thức. Dùng 1-2 gói/ngày.",
    benefits: "Tỉnh táo, tăng cường năng lượng, hỗ trợ miễn dịch nhờ nấm Chaga và Linh Chi.",
  },
  {
    id: 3,
    name: "Bách Xuân",
    slug: "bach-xuan",
    category: "thuc-pham-bo-sung",
    prices: { normal: 832582, silver: 726545, gold: 726545, super_gold: 657818 },
    points: 280,
    image: "/images/products/bach-xuan.jpg",
    description: "Thực phẩm bổ sung Bách Xuân - hỗ trợ sức khỏe toàn diện.",
    ingredients: "Hỗn hợp thảo dược quý: Nhân sâm, Linh Chi, Đông trùng hạ thảo, các vitamin và khoáng chất thiết yếu.",
    usage: "Dùng 1-2 viên/lần, 2 lần/ngày. Uống sau ăn 30 phút.",
    benefits: "Hỗ trợ tăng cường sức khỏe, nâng cao đề kháng, bổ sung dưỡng chất thiết yếu.",
  },
  {
    id: 4,
    name: "Dầu gội",
    slug: "dau-goi",
    category: "cham-soc-ca-nhan",
    prices: { normal: 490000, silver: 420000, gold: 325000, super_gold: 325000 },
    points: 125,
    image: "/images/products/dau-goi.jpg",
    description: "Dầu gội đầu thảo dược từ Vinalink, giúp tóc chắc khỏe và mềm mượt.",
    ingredients: "Chiết xuất thảo dược tự nhiên, Biotin, Keratin, Vitamin B5, tinh dầu bưởi.",
    usage: "Làm ướt tóc, lấy lượng vừa đủ xoa đều lên tóc, massage nhẹ 2-3 phút rồi xả sạch.",
    benefits: "Làm sạch da đầu, giảm gàu, giảm rụng tóc, tóc mềm mượt và bóng khỏe.",
  },
  {
    id: 5,
    name: "Dầu xả",
    slug: "dau-xa",
    category: "cham-soc-ca-nhan",
    prices: { normal: 490000, silver: 420000, gold: 325000, super_gold: 325000 },
    points: 125,
    image: "/images/products/dau-xa.jpg",
    description: "Dầu xả thảo dược giúp tóc suôn mượt, dưỡng tóc từ gốc đến ngọn.",
    ingredients: "Keratin, Vitamin E, dầu Argan, chiết xuất hoa hồng, Panthenol.",
    usage: "Sau khi gội đầu, thoa đều dầu xả lên tóc, để 2-3 phút rồi xả sạch.",
    benefits: "Dưỡng tóc suôn mượt, giảm xơ rối, phục hồi tóc hư tổn, hương thơm lâu.",
  },
  {
    id: 6,
    name: "Xịt thơm miệng",
    slug: "xit-thom-mieng",
    category: "cham-soc-ca-nhan",
    prices: { normal: 810000, silver: 672000, gold: 528000, super_gold: 528000 },
    points: 180,
    image: "/images/products/xit-thom-mieng.jpg",
    description: "Xịt thơm miệng tiện lợi, mang lại hơi thở thơm mát tức thì.",
    ingredients: "Tinh dầu bạc hà, chiết xuất trà xanh, Xylitol, nước tinh khiết.",
    usage: "Xịt 1-2 lần vào khoang miệng khi cần thiết.",
    benefits: "Khử mùi hôi miệng, mang lại hơi thở thơm mát, tiện lợi mang theo.",
  },
  {
    id: 7,
    name: "Xịt khử mùi",
    slug: "xit-khu-mui",
    category: "cham-soc-ca-nhan",
    prices: { normal: 750000, silver: 620000, gold: 510000, super_gold: 510000 },
    points: 180,
    image: "/images/products/xit-khu-mui.jpg",
    description: "Xịt khử mùi cơ thể, giữ cơ thể thơm mát suốt ngày dài.",
    ingredients: "Chiết xuất thảo dược, tinh dầu tự nhiên, kháng khuẩn tự nhiên.",
    usage: "Xịt lên vùng da cần khử mùi (nách, cổ, ngực) sau khi tắm hoặc khi cần.",
    benefits: "Khử mùi hiệu quả, kháng khuẩn, không gây kích ứng, hương thơm tự nhiên.",
  },
  {
    id: 8,
    name: "Dung dịch vệ sinh phụ nữ",
    slug: "ve-sinh-phu-nu",
    category: "cham-soc-ca-nhan",
    prices: { normal: 235000, silver: 190000, gold: 155000, super_gold: 155000 },
    points: 55,
    image: "/images/products/ve-sinh-phu-nu.jpg",
    description: "Dung dịch vệ sinh phụ nữ dịu nhẹ, bảo vệ vùng kín hàng ngày.",
    ingredients: "Chiết xuất trà xanh, Lactic Acid, chiết xuất lô hội, nước tinh khiết.",
    usage: "Sử dụng hàng ngày khi tắm. Lấy lượng vừa đủ, rửa nhẹ nhàng vùng kín rồi xả sạch.",
    benefits: "Làm sạch dịu nhẹ, cân bằng pH, kháng khuẩn, ngăn ngừa viêm nhiễm.",
  },
  {
    id: 9,
    name: "Son dưỡng môi",
    slug: "son-duong-moi",
    category: "cham-soc-ca-nhan",
    prices: { normal: 185000, silver: 155000, gold: 125000, super_gold: 125000 },
    points: 45,
    image: "/images/products/son-duong-moi.jpg",
    description: "Son dưỡng môi giúp đôi môi mềm mịn, không bị khô nứt.",
    ingredients: "Sáp ong, Vitamin E, dầu jojoba, bơ hạt mỡ, chiết xuất hoa hồng.",
    usage: "Thoa đều lên môi khi cần. Có thể dùng trước khi trang điểm hoặc trước khi ngủ.",
    benefits: "Dưỡng ẩm sâu, làm mềm môi, chống nứt nẻ, bảo vệ môi khỏi tác nhân bên ngoài.",
  },
  {
    id: 10,
    name: "VHealth Socola",
    slug: "vhealth-socola",
    category: "thuc-pham-bo-sung",
    prices: { normal: 652909, silver: 567491, gold: 540000, super_gold: 510000 },
    points: 207,
    image: "/images/products/vhealth-socola.jpg",
    description: "Thực phẩm bổ sung VHealth hương Socola 20g/hộp. Bột dinh dưỡng đa năng pha với nước.",
    ingredients: "Moi goi 25g chua: Kem khong sua (non dairy creamer); bot hon hop cac hat (Gao te, dau nanh, dau xanh, dau lang, hanh nhan, dau Ha Lan); Maltodextrin; Protein dau Ha Lan; chat xo hoa tan (FOS (oligofructose), Inulin); bot sua gay; Yen mach; bot ca cao; chat tao ngot tu nhien (Fructose); huong lieu TPTH (huong socola, huong vani); chat lam day (gom gua, gom xanthan); Hoang ky (Astragalus membranaceus); Canxi (tu tao bien) 125mg; Natri clorid; Dang sam (Codonopsis pilosula); chat chong dong von (silicon dioxide); Immulata (Nam hau thu, Tao Nannochloropsis sp. tuoi, lactose monohydrate); Vitamin C 15mg; Nam Chaga (Inonotus obliquus); IMCDeltaImmune (Vach te bao Lactobacillus rhamnosus, maltodextrin); bot chiet xuat Nam nguu chuong chi (Antrodia cinnamomea mycelia); Magie (Magie lactat dihydrat) 10mg; chat tao ngot tong hop (Sucralose); Kem (Kem gluconat) 2mg; Vitamin B1 (Thiamin mononitrat) 0.5mg; Vitamin B2 (Riboflavin) 0.5mg; Vitamin B6 (Pyridoxin hydroclorid) 0.5mg.",
    usage: "Pha 1 goi Vhealth voi khoang 150ml nuoc. Co the pha voi nuoc loc, sua, nuoc hoa qua... khuay deu va thuong thuc. Ngon hon khi pha voi nuoc am. Dung cho nguoi lon, tre em tren 6 tuoi. Co the pha 1-2 goi/lan, ngay dung 1-3 goi hoac nhieu hon tuy nhu cau. Tre em su dung 1 goi/ngay, chia 1-2 lan. Khoi luong tinh: 375g (15 goi x 25g); 500g (20 goi x 25g); 750g (30 goi x 25g).",
    benefits: "Bo sung dinh duong da dang, tang cuong suc de khang, ho tro tieu hoa, cung cap nang luong. Thuc pham nay khong phai la thuoc va khong co tac dung thay the thuoc chua benh.",
  },
  {
    id: 11,
    name: "VHealth Trà Xanh",
    slug: "vhealth-tra-xanh",
    category: "thuc-pham-bo-sung",
    prices: { normal: 652909, silver: 567491, gold: 540000, super_gold: 510000 },
    points: 207,
    image: "/images/products/vhealth-traxanh.jpg",
    description: "Thực phẩm bổ sung VHealth hương Trà xanh 20g/hộp. Bột dinh dưỡng thơm ngon.",
    ingredients: "Moi goi 25g chua: Kem khong sua (Non dairy creamer); bot hon hop cac hat (Gao te, dau nanh, dau xanh, dau lang, hanh nhan, dau Ha Lan); maltodextrin; protein dau Ha Lan; chat xo hoa tan (FOS (oligofructose), Inulin); bot sua gay; yen mach; chat tao ngot tu nhien (Fructose); huong lieu TPTH (huong tra xanh, huong tra xanh matcha, huong sua); bot Matcha; chat lam day (gom xanthan, gom gua); Hoang ky (Astragalus membranaceus); Canxi (tu tao bien) 125mg; Dang sam (Codonopsis pilosula); natri clorid; chat chong dong von (silicon dioxide); Immulata (Nam hau thu, Tao Nannochloropsis sp. tuoi, lactose monohydrate); Vitamin C 15mg; Nam Chaga (Inonotus obliquus); IMCDeltaImmune (Vach te bao Lactobacillus rhamnosus, maltodextrin); bot chiet xuat Nam nguu chuong chi (Antrodia cinnamomea mycelia); Magie (Magie lactat dihydrat) 10mg; chat tao ngot tong hop (Sucralose); Kem (kem gluconat) 2mg; Vitamin B1 (Thiamin mononitrat) 0.5mg; Vitamin B2 (Riboflavin) 0.5mg; Vitamin B6 (Pyridoxin hydroclorid) 0.5mg.",
    usage: "Pha 1 goi Vhealth voi khoang 150ml nuoc. Co the pha voi nuoc loc, sua, nuoc hoa qua... khuay deu va thuong thuc. Ngon hon khi pha voi nuoc am. Dung cho nguoi lon, tre em tren 6 tuoi. Co the pha 1-2 goi/lan, ngay dung 1-3 goi hoac nhieu hon tuy nhu cau. Tre em su dung 1 goi/ngay, chia 1-2 lan.",
    benefits: "Bo sung dinh duong, chong oxy hoa tu tra xanh Matcha, tang cuong mien dich, ho tro tieu hoa. Thuc pham nay khong phai la thuoc va khong co tac dung thay the thuoc chua benh.",
  },
  {
    id: 12,
    name: "Quantum Hydrogen",
    slug: "quantum-hydrogen",
    category: "thuc-pham-bo-sung",
    prices: { normal: 780000, silver: 579273, gold: 530182, super_gold: 481091 },
    points: 205,
    image: "/images/products/quantum.jpg",
    description: "Nước uống Hydrogen Quantum 10g/hộp - 1 thùng 10 túi. Nước có cấu trúc phân tử nhỏ chứa Hydrogen.",
    ingredients: "Nước có cấu trúc dạng cụm phân tử nhỏ, chứa Hydrogen hoạt tính.",
    usage: "Sử dụng làm nước uống hàng ngày. Dùng trực tiếp, uống ngay khi mở nắp. Đóng kín sau mỗi lần sử dụng, nên dùng trong 4h sau khi mở.",
    benefits: "Bổ sung Hydrogen cho cơ thể, chống oxy hóa, hỗ trợ trao đổi chất, thanh lọc cơ thể.",
  },
  {
    id: 13,
    name: "Genecel Max",
    slug: "genecel-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 489927, silver: 440836, gold: 391745, super_gold: 342655 },
    points: 160,
    image: "/images/products/genecel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Genecel® Max - hỗ trợ tế bào gốc, chống lão hóa.",
    ingredients: "Moi vien: IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Taurine 300mg, Cao Bach thuoc 100mg, Cao Linh chi 100mg, Cao Kho sam bac 90mg, Chiet xuat Pine bark (Thong do) 30mg, Acid alpha Lipoic 20mg. Phu lieu: cellulose vi tinh the, silicon dioxid, magnesi stearat, talc, povidon, HPMC, PEG, titan dioxyd, brilliant blue FCF.",
    usage: "2-4 vien/ngay, chia 2 lan. Truoc bua an 30 phut hoac sau an 1 gio. Lien tuc 3-6 thang. XNCB: 3196/2021/DKSP.",
    benefits: "Ho tro tang cuong suc khoe, tang cuong suc de khang, ho tro chong oxy hoa, ho tro han che lao hoa.",
  },
  {
    id: 14,
    name: "Detoxmune Max",
    slug: "detoxmune-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 584182, silver: 505637, gold: 480109, super_gold: 431018 },
    points: 185,
    image: "/images/products/detoxmune.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Detoxmune® Max - hỗ trợ bảo vệ gan, giải độc gan.",
    ingredients: "Moi vien: IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Cao Tho phuc linh 375mg, Calci alginat 150mg, L-Carnitin fumarat 22.5mg, L-Arginin (L-Arginine hydrochloride) 18.5mg, Acid alpha Lipoic 15mg. Phu lieu: natri succinat hexahydrat, cellulose vi tinh the, silicon dioxid, talc, magnesi stearat, lactose, PVA, povidon, HPMC, PEG, titan dioxyd, polysorbate 80, mau brilliant blue FCF, tartrazin yellow.",
    usage: "1 vien/lan, 1-2 lan/ngay. Truoc an 30 phut hoac sau an 1 gio. Lien tuc 3-6 thang. XNCB: 4302/2021/DKSP.",
    benefits: "Ho tro bao ve gan, ho tro giai doc gan, ho tro tang cuong chuc nang gan trong truong hop viem gan, uong nhieu ruou, dung thuoc gay hai cho gan. Doi tuong: nguoi viem gan, uong nhieu bia ruou, me day man ngua, vang da do chuc nang gan kem.",
  },
  {
    id: 15,
    name: "Cardiopro Max",
    slug: "cardiopro-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 519382, silver: 441818, gold: 402545, super_gold: 353455 },
    points: 155,
    image: "/images/products/cardiopro.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Cardiopro® Max - hỗ trợ tim mạch, lưu thông khí huyết.",
    ingredients: "Moi vien: IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Cao Hoang ba 150mg, Cao Dan sam 150mg, Magnesi lactat dihydrat (tuong duong 9mg Magnesi) 90mg, Cao Hoang dang 75mg, Cao Natto (tu dau tuong len men) 75mg, L-Carnitin fumarat 37.5mg. Phu lieu: lactose, CPC, talc, silicon dioxid, magnesi stearat, povidon, HPMC, pouceau 4R, tartrazin yellow, PVA, PEG, titan dioxyd, polysorbate 80.",
    usage: "2-4 vien/ngay, chia 2 lan. Truoc bua an 30 phut hoac sau an 1 gio. Lien tuc 3-6 thang. Khong dung cho nguoi mau kho dong, nguoi phau thuat, phu nu mang thai, rong kinh. XNCB: 4348/2021/DKSP.",
    benefits: "Ho tro hoat huyet, tang cuong luu thong khi huyet, giam mo mau, giam nguy co xo vua dong mach, bao ve tim mach.",
  },
  {
    id: 16,
    name: "Jointlink Max",
    slug: "jointlink-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 530182, silver: 461455, gold: 412364, super_gold: 363273 },
    points: 155,
    image: "/images/products/jointlink.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Jointlink® Max - hỗ trợ xương khớp.",
    ingredients: "Moi vien: IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Cao Bach truat 300mg, Cao Khuong hoat 185mg, Cao Day dau xuong 105mg, Khuong hoang (bot) 75mg, Cao Nhan sam An Do 37.5mg, Cao Cam thao bac 37.5mg, Cao Sinh khuong 30mg, Vitamin K2 (Menaquinone-7) 7.5mcg. Phu lieu: Magnesium carbonate, cellulose vi tinh the, CPC, silicon dioxid, talc, magnesi stearat, ethyl cellulose, tartrazine.",
    usage: "2-4 vien/ngay, chia 2 lan. Truoc bua an 30 phut hoac sau an 1 gio. Lien tuc 3-6 thang. XNCB: 3478/2021/DKSP.",
    benefits: "Ho tro giam dau nhuc xuong khop, ho tro lam cham qua trinh thoai hoa khop.",
  },
  {
    id: 17,
    name: "Lacttocol Max",
    slug: "lacttocol-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 441818, silver: 382909, gold: 343636, super_gold: 294545 },
    points: 130,
    image: "/images/products/lacttocol.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Lacttocol® Max - hỗ trợ đường ruột, tiêu hóa.",
    ingredients: "Moi vien: IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Cao Bach truat 135mg, Cao Bach phuc linh 60mg. Phu lieu: Lactose, cellulose vi tinh the, calci phosphat, tinh bot bap, mang bao CPC, povidon, talc, magnesi stearat, sunset yellow.",
    usage: "2-4 vien/ngay, chia 2 lan. Truoc bua an 30 phut hoac sau an 1 gio. Lien tuc 3-6 thang. XNCB: 3440/2021/DKSP.",
    benefits: "Ho tro can bang he vi sinh duong ruot, tang cuong tieu hoa, giam roi loan tieu hoa.",
  },
  {
    id: 18,
    name: "Sữa tắm nữ",
    slug: "sua-tam-nu",
    category: "cham-soc-ca-nhan",
    prices: { normal: 352000, silver: 299000, gold: 255000, super_gold: 229000 },
    points: 100,
    image: "/images/products/sua-tam-nu.jpg",
    description: "Sữa tắm dành cho nữ, hương thơm nhẹ nhàng, dưỡng da mềm mịn.",
    ingredients: "Chiết xuất hoa hồng, Vitamin E, tinh dầu lavender, Glycerin, chiết xuất lô hội.",
    usage: "Lấy lượng vừa đủ, tạo bọt và massage nhẹ nhàng lên da, sau đó xả sạch.",
    benefits: "Làm sạch da dịu nhẹ, dưỡng ẩm, da mềm mịn, hương thơm quyến rũ.",
  },
  {
    id: 19,
    name: "Sữa tắm nam",
    slug: "sua-tam-nam",
    category: "cham-soc-ca-nhan",
    prices: { normal: 352000, silver: 299000, gold: 255000, super_gold: 229000 },
    points: 100,
    image: "/images/products/sua-tam-nam.jpg",
    description: "Sữa tắm dành cho nam, sảng khoái, năng động suốt ngày.",
    ingredients: "Than hoạt tính, tinh dầu bạc hà, Menthol, chiết xuất trà xanh, Glycerin.",
    usage: "Lấy lượng vừa đủ, tạo bọt và massage lên da, sau đó xả sạch.",
    benefits: "Làm sạch sâu, kiểm soát dầu thừa, sảng khoái, hương nam tính.",
  },
  {
    id: 20,
    name: "Green Quantum (Diệp lục)",
    slug: "green-quantum",
    category: "thuc-pham-bo-sung",
    prices: { normal: 192436, silver: 164945, gold: 133527, super_gold: 122727 },
    points: 54,
    image: "/images/products/diep-luc.jpg",
    description: "Green Quantum - Nước uống cô đặc diệp lục. Bổ sung chất xơ và diệp lục tố.",
    ingredients: "Nuoc tinh khiet, chat lam day (glycerol, gom xanthan), Tao Nannochloropsis sp., Arginin hydroclorid, Natri erythorbat (chong oxy hoa), Sodium copper chlorophyllin, PEG-40 hydrogenated castor oil, Trinatri citrat, IMCDeltaimmune (vach te bao Lactobacillus rhamnosus, maltodextrin, manitol), tinh dau bac ha, huong bac ha tu nhien. The tich: 150ml.",
    usage: "Pha 1 gói với 200ml nước, khuấy đều. Dùng 1-2 gói/ngày.",
    benefits: "Thanh lọc cơ thể, bổ sung chất xơ, hỗ trợ tiêu hóa, cung cấp diệp lục tố thiên nhiên.",
  },
  {
    id: 21,
    name: "Kidsmune Max",
    slug: "kidsmune-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 505636, silver: 451636, gold: 407455, super_gold: 378000 },
    points: 168,
    image: "/images/products/genecel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Kidsmune® Max - hỗ trợ miễn dịch cho trẻ em.",
    ingredients: "Moi goi: Inulin 405mg, IMCDelta-immune (vach te bao Lactobacillus rhamnosus) 300mg, Sua non (Colostrum) 200mg, Cao Hoang ky 155mg, Cao Diep ca 130mg, Galacto Oligosaccharide 90mg, L-Lysine (L-Lysine Hydrochloride) 50mg, Taurine 50mg, FOS 10mg, DHA 5mg, Kem (Zinc gluconate) 2mg, Lutein 1mg, Folic Acid 130mcg. Phu lieu: sucrose, bot cacao, huong tong hop, silicon dioxid, caramel, povidon, sucralose.",
    usage: "Tre 3-4 tuoi: 1 goi/lan x 1-2 lan/ngay. Tre 5-9 tuoi: 1 goi/lan x 2-3 lan/ngay. Tre 10 tuoi tro len: 2 goi/lan x 2 lan/ngay. Pha vao nuoc hoac sua. CBSP: 1415/2022/DKSP.",
    benefits: "Tang cuong mien dich cho tre, ho tro phat trien, giam nguy co om vat. Chua Sua non, Lysine, DHA, Kem giup tre phat trien toan dien.",
  },
  {
    id: 22,
    name: "Mindenergy Max",
    slug: "mindenergy-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 495818, silver: 446727, gold: 402545, super_gold: 373091 },
    points: 158,
    image: "/images/products/mindenergy.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Mindenergy® Max - hỗ trợ não bộ, tăng cường trí nhớ.",
    ingredients: "Moi vien: Fibrinolytic enzyme tu ImmuBeans 450FU, DeltaImmune (vach te bao Lactobacillus rhamnosus) 400mg, Cao Nguu tat 125mg, Chiet xuat Bacopa monnieri 90mg, L-Carnitine (dang L-Carnitine fumarate) 60mg, Cao Dinh lang 55mg, DHA (Docosahexaenoic acid) 10mg. Phu lieu: cellulose vi tinh the, povidon, Opadry AMB II white, talc, silicon dioxid, magnesi stearat.",
    usage: "1 vien/lan x 1-3 lan/ngay. Uong khi doi: sau an 2 gio hoac truoc an 30 phut. Uong nguyen vien. Hoi y kien bac sy neu dang chay mau hoac dung thuoc chong dong mau. Phu nu co thai khong nen su dung. CBSP: 1414/2022/DKSP.",
    benefits: "Ho tro tuan hoan nao, tang cuong tri nho va tap trung, giam suy giam tri nho.",
  },
  {
    id: 23,
    name: "Manlink Max",
    slug: "manlink-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 525818, silver: 463636, gold: 418545, super_gold: 354727 },
    points: 175,
    image: "/images/products/manlink.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Man-Link® Max - hỗ trợ sức khỏe nam giới.",
    ingredients: "Moi vien: L-Arginine.HCl 450mg, IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 150mg, Cao Bach tat le 90mg, Cao Dam duong hoac 75mg, Cao Ba kich 75mg, Fenugreek seed extract (chiet xuat hat Co ca ri) 75mg, Cao Nhan sam 25mg, DHEA (Dehydroepiandrosterone) 10mg, Kem (dang Zn Gluconate) 10mg, Dong trung ha thao 5mg. Phu lieu: Oxyd Magnesi, talc, magnesi stearat, silicon dioxid, Lactose, Opadry AMB red, cellulose vi tinh the, crospovidon.",
    usage: "2-3 vien/ngay chia 2-3 lan. Truoc bua an 30 phut hoac sau an 1 gio. Khong dung cho nguoi duoi 18 tuoi, nguoi co tien su huyet ap cao, benh tim mach, tieu duong. CBSP: 1752/2022/DKSP.",
    benefits: "Ho tro tang cuong sinh luc nam gioi, nang cao suc khoe phai manh.",
  },
  {
    id: 24,
    name: "Oricode Sâm",
    slug: "oricode-sam",
    category: "thuc-pham-bo-sung",
    prices: { normal: 625455, silver: 530182, gold: 451637, super_gold: 406473 },
    points: 175,
    image: "/images/products/bach-xuan.jpg",
    description: "Oricode Sâm - sản phẩm từ nhân sâm quý, bổ sung năng lượng và sức đề kháng.",
    ingredients: "Chiết xuất nhân sâm Hàn Quốc, mật ong, Royal Jelly, Vitamin nhóm B.",
    usage: "Dùng 1-2 gói/ngày. Pha với nước ấm hoặc uống trực tiếp.",
    benefits: "Bổ sung năng lượng, tăng sức đề kháng, chống mệt mỏi, nâng cao thể lực.",
  },
  {
    id: 25,
    name: "VTopcan",
    slug: "vtopcan",
    category: "bao-ve-suc-khoe",
    prices: { normal: 8826545, silver: 7658182, gold: 6872727, super_gold: 6185455 },
    points: 2850,
    image: "/images/products/vtopcan.jpg",
    description: "Thực phẩm bảo vệ sức khỏe VTopcan - gói 120 gói. Sản phẩm cao cấp nhất của Vinalink.",
    ingredients: "Moi goi 15g: Fucoidan 205mg, IMCDeltaImmune (vach te bao Lactobacillus rhamnosus) 100mg, Protein dau nanh chua Lunasin 100mg, Cao La tre (Bambusa sp.) 50mg, Tao Nannochloropsis sp. 25mg, Cao Sa (Cymbopogon citratus) 25mg, Cao Hoa du du duc (Carica papaya) 5mg, Chiet xuat nam Nguu Chuong chi (Antrodia cinnamomea) 5mg, Selen (Selenium yeast) 20mcg. Phu lieu: Maltodextrin, mach nha, huong lieu, citric acid, kali sorbate, gellan gum.",
    usage: "Theo hướng dẫn chi tiết trên bao bì sản phẩm. Liên tục 3-6 tháng.",
    benefits: "Bảo vệ sức khỏe toàn diện, hỗ trợ miễn dịch mạnh mẽ, phù hợp cho người cần chăm sóc đặc biệt.",
  },
  {
    id: 26,
    name: "VSportGel",
    slug: "vsportgel",
    category: "bao-ve-suc-khoe",
    prices: { normal: 1914545, silver: 1659273, gold: 1497273, super_gold: 1364727 },
    points: 620,
    image: "/images/products/vsportgel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe VSportGel - 50 gói. Hỗ trợ vận động viên và người tập thể thao.",
    ingredients: "Moi goi 15g: L-Carnitine fumarate 150mg, Taurine 150mg, Cao Dinh lang (Polyscias fruticosa) 100mg, L-Arginine alpha ketoglutarate 55mg, Magnesi clorid 32mg, N.N-Dimethylglycine (DMG) 30mg, BCAA (Leucine, Isoleucine, Valine) 25mg, D-Ribose 25mg, L-Citrulline DL-malate 20mg, ElevATP (chiet xuat tao va than bun) 20mg, Natri clorid 9.6mg, Vitamin B5 5mg, Tao Nannochloropsis sp. 5mg, Kem gluconat 1.5mg, Kali clorid 1.6mg, Vitamin B1 0.3mg, Vitamin B6 0.3mg.",
    usage: "1-2 gói/ngày. Pha với nước hoặc uống trực tiếp, trước hoặc sau tập luyện.",
    benefits: "Hỗ trợ phục hồi cơ khớp, tăng cường sức bền, bảo vệ sụn khớp cho người vận động nhiều.",
  },
  {
    id: 27,
    name: "TOPAPRO (Bột Protein)",
    slug: "topapro",
    category: "thuc-pham-bo-sung",
    prices: { normal: 682364, silver: 603818, gold: 574364, super_gold: 540000 },
    points: 220,
    image: "/images/products/topapro.jpg",
    description: "Thực phẩm bổ sung TOPAPRO - Bột protein chất lượng cao.",
    ingredients: "Moi goi 25g: Protein dau Ha Lan, Maltodextrin, kem thuc vat, acid amin hon hop (Lysin HCl, Threonin, Histidin, Leucin, Valin, Phenylalanin, Isoleucin, Methionin, Tryptophan), ProteoSMART 200mg, hon hop bot hat (gao te, dau xanh, gao lut, dau Ha Lan, dau lang, dau trang, hat sen, hanh nhan, hat bi do, hat oc cho), AminbioCer-VIDS 150mg, Bio-She 60mg, Inulin, bot tao Chlorella pyrenoidosa, bot ca cao, Kem bisglycinate. Chat lam day: Gom gua, PVA, Gom xanthan.",
    usage: "Pha 1 gói với 200ml nước hoặc sữa, khuấy đều. Dùng 1-2 gói/ngày, trước hoặc sau tập luyện.",
    benefits: "Bổ sung protein chất lượng cao, hỗ trợ phát triển cơ bắp, phục hồi sau tập luyện.",
  },
  {
    id: 28,
    name: "Nước tẩy trang Orico Micellar Water",
    slug: "nuoc-tay-trang",
    category: "cham-soc-da",
    prices: { normal: 587127, silver: 489927, gold: 440836, super_gold: 397636 },
    points: 185,
    image: "/images/products/nuoc-tay-trang.jpg",
    description: "Nước tẩy trang Orico Micellar Water - làm sạch sâu, dịu nhẹ cho da.",
    ingredients: "Water (Nuoc Quantum), Babassu oil glycereth-8 esters, PEG-40 hydrogenated castor oil, PEG-7 glyceryl cocoate, Panthenol, Panax ginseng extract (Chiet xuat Sam Trieu Tien), Alteromonas ferment extract, Illicium verum fruit extract (Hoi), Calendula officinalis flower extract (Cuc kim tien), Scutellaria baicalensis root extract (Hoang cam), Sodium PCA, Allantoin, Tocopheryl acetate, Ascorbyl glucoside, Glycerin, Ethylhexylglycerin, Disodium EDTA, Phenoxyethanol. Khong chua con va paraben.",
    usage: "Thấm nước tẩy trang lên bông cotton, lau nhẹ nhàng lên mặt cho đến khi sạch.",
    benefits: "Làm sạch makeup hiệu quả, không gây khô da, dưỡng ẩm nhẹ, phù hợp da nhạy cảm.",
  },
  {
    id: 29,
    name: "Nước hoa hồng Orico Toner",
    slug: "nuoc-hoa-hong-toner",
    category: "cham-soc-da",
    prices: { normal: 540000, silver: 451636, gold: 407455, super_gold: 368182 },
    points: 170,
    image: "/images/products/toner.jpg",
    description: "Nước hoa hồng Orico Toner - cân bằng da, se khít lỗ chân lông.",
    ingredients: "Water (Nuoc Quantum), Propanediol, Niacinamide, Panax ginseng extract (Sam Trieu Tien), Alteromonas ferment extract, Trifolium pratense flower extract (Co ba la), Carica papaya fruit extract (Du du), Saccharide isomerate, Dihydroxypropyl arginine HCl, Allantoin, Sodium hyaluronate, Sodium PCA, Betaine, Glycerin, Butylene glycol, PEG-40 hydrogenated castor oil, Ethylhexylglycerin, Phenoxyethanol. Khong chua con va paraben.",
    usage: "Sau khi rửa mặt, thấm toner lên bông cotton hoặc tay, vỗ nhẹ lên da.",
    benefits: "Cân bằng pH da, se khít lỗ chân lông, cấp ẩm, chuẩn bị da cho các bước dưỡng tiếp theo.",
  },
  {
    id: 30,
    name: "Sữa rửa mặt Orico Cleanser",
    slug: "sua-rua-mat",
    category: "cham-soc-da",
    prices: { normal: 378000, silver: 314182, gold: 284727, super_gold: 255273 },
    points: 115,
    image: "/images/products/sua-rua-mat.jpg",
    description: "Sữa rửa mặt Orico Cleanser - làm sạch da dịu nhẹ hàng ngày.",
    ingredients: "Water (Nuoc Quantum), Sodium cocoyl isethionate, Glycerin, Stearyl alcohol, Cocamidopropyl betaine, Sodium methyl cocoyl taurate, Glycol distearate, PEG-7 glyceryl cocoate, Panax ginseng extract (Sam Trieu Tien), Trifolium pratense flower extract (Co ba la), Alteromonas ferment extract, Gluconolactone, Sodium PCA, Panthenol, Sodium hyaluronate, Betonite, Ethylhexylglycerin, Phenoxyethanol.",
    usage: "Lấy lượng vừa đủ, tạo bọt với nước, massage nhẹ nhàng lên mặt 1 phút rồi rửa sạch.",
    benefits: "Làm sạch sâu nhưng dịu nhẹ, không khô căng, kiểm soát dầu, phù hợp mọi loại da.",
  },
  {
    id: 31,
    name: "Kem chống nắng Orico Sun Screen",
    slug: "kem-chong-nang",
    category: "cham-soc-da",
    prices: { normal: 711818, silver: 561600, gold: 505636, super_gold: 456545 },
    points: 210,
    image: "/images/products/kem-chong-nang.jpg",
    description: "Kem chống nắng Orico Sun Screen - bảo vệ da khỏi tia UV.",
    ingredients: "Water (Nuoc Quantum), Cyclopentasiloxane, Ethylhexyl methoxycinnamate, Titanium dioxide, Diethylamino hydroxybenzoyl hexyl benzoate, PEG/PPG-20/15 dimethicone, Zinc oxide, Methylene bis-benzotriazolyl tetramethylbutylphenol, Panax ginseng extract (Sam Trieu Tien), Caesalpinia sappan bark extract (To moc), Alteromonas ferment extract, Sodium hyaluronate, Astaxanthin, Silica, Polymethylsilsesquioxane, Aluminum hydroxide, Phenoxyethanol.",
    usage: "Thoa đều lên da mặt và vùng da tiếp xúc ánh nắng trước 15-20 phút. Thoa lại mỗi 2-3 giờ.",
    benefits: "Bảo vệ da khỏi tia UVA/UVB, ngăn ngừa lão hóa do nắng, dưỡng ẩm, không bết dính.",
  },
  {
    id: 32,
    name: "Kem dưỡng da Orico Cream",
    slug: "kem-duong-da",
    category: "cham-soc-da",
    prices: { normal: 1030909, silver: 890000, gold: 810000, super_gold: 730000 },
    points: 300,
    image: "/images/products/kem-duong.jpg",
    description: "Kem dưỡng da Orico Cream - dưỡng ẩm sâu, chống lão hóa.",
    ingredients: "Water (Nuoc Quantum), Glycerin, Cyclopentasiloxane, Butylene glycol, Dimethicone, Hexyl 3-glyceryl ascorbate, Xylitylglucoside, Panax ginseng extract (Sam Trieu Tien), Alteromonas ferment extract, Palmitoyl dipeptide-61, Palmitoyl tripeptide-95, Allantoin, Sodium hyaluronate, Sodium PCA, Lactic acid/Glycolic acid copolymer, Caprylyl glycol, Xanthan gum, Ethylhexylglycerin, Phenoxyethanol.",
    usage: "Thoa đều lên da mặt và cổ sau bước toner và serum. Dùng sáng và tối.",
    benefits: "Dưỡng ẩm sâu, chống lão hóa, làm sáng da, cải thiện nếp nhăn, da căng mịn.",
  },
].map((p) => {
  // Merge metadata from product-meta.ts
  const meta = require("./product-meta").productMeta[p.slug];
  return {
    ...p,
    origin: meta?.origin || "Viet Nam",
    manufacturer: meta?.manufacturer || "Dang cap nhat",
    distributor: meta?.distributor || "Cong ty Co phan Tap doan Lien ket Viet Nam (Vinalink Group)",
    registration: meta?.registration || "Dang cap nhat",
  };
});

export function formatPrice(price: number): string {
  return price.toLocaleString("vi-VN");
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
