export type MembershipTier = "normal" | "silver" | "gold" | "super_gold";

export interface Product {
  id: number;
  name: string;
  slug: string;
  category: string;
  prices: Record<MembershipTier, number>;
  points: number;
  image: string;
  description: string;
  ingredients: string;
  usage: string;
  benefits: string;
}

export interface CartItem {
  product: Product;
  membership: MembershipTier;
  quantity: number;
}

export const MEMBERSHIP_LABELS: Record<MembershipTier, string> = {
  normal: "Thường",
  silver: "Bạc",
  gold: "Vàng",
  super_gold: "Siêu Vàng",
};

export const CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "thuc-pham-bo-sung", label: "Thực phẩm bổ sung" },
  { key: "bao-ve-suc-khoe", label: "Bảo vệ sức khỏe" },
  { key: "cham-soc-ca-nhan", label: "Chăm sóc cá nhân" },
  { key: "cham-soc-da", label: "Chăm sóc da (Orico)" },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Kem đánh răng VSmile",
    slug: "kem-danh-rang-vsmile",
    category: "cham-soc-ca-nhan",
    prices: { normal: 897000, silver: 780000, gold: 780000, super_gold: 702000 },
    points: 310,
    image: "/images/products/kem-danh-rang.jpg",
    description: "Kem đánh răng VSmile 150g/hộp - 5 hộp/lốc. Sản phẩm chăm sóc răng miệng cao cấp từ Vinalink.",
    ingredients: "Calcium Carbonate, Sorbitol, Silica, Sodium Lauryl Sulfate, chiết xuất thảo dược tự nhiên.",
    usage: "Đánh răng 2 lần/ngày, sáng và tối. Sử dụng lượng vừa đủ trên bàn chải.",
    benefits: "Giúp răng trắng sáng, ngăn ngừa sâu răng, bảo vệ nướu, thơm miệng lâu.",
  },
  {
    id: 2,
    name: "Cà phê Link",
    slug: "caphelink",
    category: "thuc-pham-bo-sung",
    prices: { normal: 888691, silver: 765818, gold: 765818, super_gold: 689237 },
    points: 300,
    image: "/images/products/caphelink.jpg",
    description: "Thực phẩm bổ sung Caphelink New 20g/hộp. Cà phê kết hợp các thành phần tốt cho sức khỏe.",
    ingredients: "Cà phê hòa tan, kem không sữa, đường, Nấm Chaga, Nấm Linh Chi (Ganoderma Lucidum), Đảng sâm, Maca.",
    usage: "Pha 1 gói với 150ml nước nóng, khuấy đều và thưởng thức. Dùng 1-2 gói/ngày.",
    benefits: "Tỉnh táo, tăng cường năng lượng, hỗ trợ miễn dịch nhờ nấm Chaga và Linh Chi.",
  },
  {
    id: 3,
    name: "Bách Xuân",
    slug: "bach-xuan",
    category: "thuc-pham-bo-sung",
    prices: { normal: 832582, silver: 726545, gold: 726545, super_gold: 657818 },
    points: 280,
    image: "/images/products/bach-xuan.jpg",
    description: "Thực phẩm bổ sung Bách Xuân - hỗ trợ sức khỏe toàn diện.",
    ingredients: "Hỗn hợp thảo dược quý: Nhân sâm, Linh Chi, Đông trùng hạ thảo, các vitamin và khoáng chất thiết yếu.",
    usage: "Dùng 1-2 viên/lần, 2 lần/ngày. Uống sau ăn 30 phút.",
    benefits: "Hỗ trợ tăng cường sức khỏe, nâng cao đề kháng, bổ sung dưỡng chất thiết yếu.",
  },
  {
    id: 4,
    name: "Dầu gội",
    slug: "dau-goi",
    category: "cham-soc-ca-nhan",
    prices: { normal: 490000, silver: 420000, gold: 325000, super_gold: 325000 },
    points: 125,
    image: "/images/products/dau-goi.jpg",
    description: "Dầu gội đầu thảo dược từ Vinalink, giúp tóc chắc khỏe và mềm mượt.",
    ingredients: "Chiết xuất thảo dược tự nhiên, Biotin, Keratin, Vitamin B5, tinh dầu bưởi.",
    usage: "Làm ướt tóc, lấy lượng vừa đủ xoa đều lên tóc, massage nhẹ 2-3 phút rồi xả sạch.",
    benefits: "Làm sạch da đầu, giảm gàu, giảm rụng tóc, tóc mềm mượt và bóng khỏe.",
  },
  {
    id: 5,
    name: "Dầu xả",
    slug: "dau-xa",
    category: "cham-soc-ca-nhan",
    prices: { normal: 490000, silver: 420000, gold: 325000, super_gold: 325000 },
    points: 125,
    image: "/images/products/dau-xa.jpg",
    description: "Dầu xả thảo dược giúp tóc suôn mượt, dưỡng tóc từ gốc đến ngọn.",
    ingredients: "Keratin, Vitamin E, dầu Argan, chiết xuất hoa hồng, Panthenol.",
    usage: "Sau khi gội đầu, thoa đều dầu xả lên tóc, để 2-3 phút rồi xả sạch.",
    benefits: "Dưỡng tóc suôn mượt, giảm xơ rối, phục hồi tóc hư tổn, hương thơm lâu.",
  },
  {
    id: 6,
    name: "Xịt thơm miệng",
    slug: "xit-thom-mieng",
    category: "cham-soc-ca-nhan",
    prices: { normal: 810000, silver: 672000, gold: 528000, super_gold: 528000 },
    points: 180,
    image: "/images/products/xit-thom-mieng.jpg",
    description: "Xịt thơm miệng tiện lợi, mang lại hơi thở thơm mát tức thì.",
    ingredients: "Tinh dầu bạc hà, chiết xuất trà xanh, Xylitol, nước tinh khiết.",
    usage: "Xịt 1-2 lần vào khoang miệng khi cần thiết.",
    benefits: "Khử mùi hôi miệng, mang lại hơi thở thơm mát, tiện lợi mang theo.",
  },
  {
    id: 7,
    name: "Xịt khử mùi",
    slug: "xit-khu-mui",
    category: "cham-soc-ca-nhan",
    prices: { normal: 750000, silver: 620000, gold: 510000, super_gold: 510000 },
    points: 180,
    image: "/images/products/xit-khu-mui.jpg",
    description: "Xịt khử mùi cơ thể, giữ cơ thể thơm mát suốt ngày dài.",
    ingredients: "Chiết xuất thảo dược, tinh dầu tự nhiên, kháng khuẩn tự nhiên.",
    usage: "Xịt lên vùng da cần khử mùi (nách, cổ, ngực) sau khi tắm hoặc khi cần.",
    benefits: "Khử mùi hiệu quả, kháng khuẩn, không gây kích ứng, hương thơm tự nhiên.",
  },
  {
    id: 8,
    name: "Dung dịch vệ sinh phụ nữ",
    slug: "ve-sinh-phu-nu",
    category: "cham-soc-ca-nhan",
    prices: { normal: 235000, silver: 190000, gold: 155000, super_gold: 155000 },
    points: 55,
    image: "/images/products/ve-sinh-phu-nu.jpg",
    description: "Dung dịch vệ sinh phụ nữ dịu nhẹ, bảo vệ vùng kín hàng ngày.",
    ingredients: "Chiết xuất trà xanh, Lactic Acid, chiết xuất lô hội, nước tinh khiết.",
    usage: "Sử dụng hàng ngày khi tắm. Lấy lượng vừa đủ, rửa nhẹ nhàng vùng kín rồi xả sạch.",
    benefits: "Làm sạch dịu nhẹ, cân bằng pH, kháng khuẩn, ngăn ngừa viêm nhiễm.",
  },
  {
    id: 9,
    name: "Son dưỡng môi",
    slug: "son-duong-moi",
    category: "cham-soc-ca-nhan",
    prices: { normal: 185000, silver: 155000, gold: 125000, super_gold: 125000 },
    points: 45,
    image: "/images/products/son-duong-moi.jpg",
    description: "Son dưỡng môi giúp đôi môi mềm mịn, không bị khô nứt.",
    ingredients: "Sáp ong, Vitamin E, dầu jojoba, bơ hạt mỡ, chiết xuất hoa hồng.",
    usage: "Thoa đều lên môi khi cần. Có thể dùng trước khi trang điểm hoặc trước khi ngủ.",
    benefits: "Dưỡng ẩm sâu, làm mềm môi, chống nứt nẻ, bảo vệ môi khỏi tác nhân bên ngoài.",
  },
  {
    id: 10,
    name: "VHealth Socola",
    slug: "vhealth-socola",
    category: "thuc-pham-bo-sung",
    prices: { normal: 652909, silver: 567491, gold: 540000, super_gold: 510000 },
    points: 207,
    image: "/images/products/vhealth-socola.jpg",
    description: "Thực phẩm bổ sung VHealth hương Socola 20g/hộp. Bột dinh dưỡng đa năng pha với nước.",
    ingredients: "Kem không sữa, bột gạo, đậu nành, đậu xanh, protein đậu Hà Lan, bột sữa gầy, yến mạch, bột ca cao, Vitamin B1, B2, B6, Vitamin C, Magiê, Kẽm, Hoàng kỳ, Đảng sâm, Nấm Chaga, Immulata.",
    usage: "Pha 1 gói VHealth với khoảng 150ml nước, khuấy đều. Người lớn và trẻ em trên 6 tuổi: 1-2 gói/lần, 1-3 gói/ngày. Ngon hơn khi pha với nước ấm.",
    benefits: "Bổ sung dinh dưỡng đa dạng, tăng cường sức đề kháng, hỗ trợ tiêu hóa, cung cấp năng lượng.",
  },
  {
    id: 11,
    name: "VHealth Trà Xanh",
    slug: "vhealth-tra-xanh",
    category: "thuc-pham-bo-sung",
    prices: { normal: 652909, silver: 567491, gold: 540000, super_gold: 510000 },
    points: 207,
    image: "/images/products/vhealth-traxanh.jpg",
    description: "Thực phẩm bổ sung VHealth hương Trà xanh 20g/hộp. Bột dinh dưỡng thơm ngon.",
    ingredients: "Kem không sữa, bột gạo, đậu nành, đậu xanh, protein đậu Hà Lan, bột sữa gầy, yến mạch, bột trà xanh Matcha, Vitamin B1, B2, B6, Vitamin C, Magiê, Kẽm, Hoàng kỳ, Đảng sâm, Nấm Chaga, Immulata.",
    usage: "Pha 1 gói VHealth với khoảng 150ml nước, khuấy đều. Người lớn và trẻ em trên 6 tuổi: 1-2 gói/lần, 1-3 gói/ngày.",
    benefits: "Bổ sung dinh dưỡng, chống oxy hóa từ trà xanh, tăng cường miễn dịch, hỗ trợ tiêu hóa.",
  },
  {
    id: 12,
    name: "Quantum Hydrogen",
    slug: "quantum-hydrogen",
    category: "thuc-pham-bo-sung",
    prices: { normal: 780000, silver: 579273, gold: 530182, super_gold: 481091 },
    points: 205,
    image: "/images/products/quantum.jpg",
    description: "Nước uống Hydrogen Quantum 10g/hộp - 1 thùng 10 túi. Nước có cấu trúc phân tử nhỏ chứa Hydrogen.",
    ingredients: "Nước có cấu trúc dạng cụm phân tử nhỏ, chứa Hydrogen hoạt tính.",
    usage: "Sử dụng làm nước uống hàng ngày. Dùng trực tiếp, uống ngay khi mở nắp. Đóng kín sau mỗi lần sử dụng, nên dùng trong 4h sau khi mở.",
    benefits: "Bổ sung Hydrogen cho cơ thể, chống oxy hóa, hỗ trợ trao đổi chất, thanh lọc cơ thể.",
  },
  {
    id: 13,
    name: "Genecel Max",
    slug: "genecel-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 489927, silver: 440836, gold: 391745, super_gold: 342655 },
    points: 160,
    image: "/images/products/genecel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Genecel® Max - hỗ trợ tế bào gốc, chống lão hóa.",
    ingredients: "IMCDeltaImmune (vách tế bào vi khuẩn Lactobacillus rhamnosus), Resveratrol, Coenzyme Q10, chiết xuất nho, Vitamin E.",
    usage: "Dùng 1-2 viên/lần, 2 lần/ngày. Uống trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ tái tạo tế bào, chống lão hóa, tăng cường miễn dịch, bảo vệ cơ thể ở cấp tế bào.",
  },
  {
    id: 14,
    name: "Detoxmune Max",
    slug: "detoxmune-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 584182, silver: 505637, gold: 480109, super_gold: 431018 },
    points: 185,
    image: "/images/products/detoxmune.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Detoxmune® Max - hỗ trợ bảo vệ gan, giải độc gan.",
    ingredients: "IMCDeltaImmune 400mg, Cao Thổ phục linh 375mg, Calci alginat 150mg, L-Carnitin fumarat 22.5mg, L-Arginin 18.5mg, Acid alpha Lipoic 15mg.",
    usage: "1 viên/lần, 1-2 lần/ngày. Trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ bảo vệ gan, giải độc gan, tăng cường chức năng gan. Phù hợp cho người viêm gan, uống nhiều rượu bia, mề đay mẩn ngứa.",
  },
  {
    id: 15,
    name: "Cardiopro Max",
    slug: "cardiopro-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 519382, silver: 441818, gold: 402545, super_gold: 353455 },
    points: 155,
    image: "/images/products/cardiopro.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Cardiopro® Max - hỗ trợ tim mạch, lưu thông khí huyết.",
    ingredients: "IMCDeltaImmune 400mg, Cao Hoàng bá 150mg, Cao Đan sâm 150mg, Magnesi lactat 90mg, Cao Hoàng đằng 75mg, Cao Natto 75mg, L-Carnitin fumarat 37.5mg.",
    usage: "2-4 viên/ngày, chia 2 lần. Trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ hoạt huyết, tăng cường lưu thông khí huyết, giảm mỡ máu, giảm nguy cơ xơ vữa động mạch, bảo vệ tim mạch.",
  },
  {
    id: 16,
    name: "Jointlink Max",
    slug: "jointlink-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 530182, silver: 461455, gold: 412364, super_gold: 363273 },
    points: 155,
    image: "/images/products/jointlink.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Jointlink® Max - hỗ trợ xương khớp.",
    ingredients: "IMCDeltaImmune, Glucosamine, Chondroitin, Collagen type II, Canxi, Vitamin D3, chiết xuất thảo dược.",
    usage: "2-4 viên/ngày, chia 2 lần. Trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ giảm đau nhức xương khớp, tăng cường sụn khớp, hỗ trợ vận động linh hoạt.",
  },
  {
    id: 17,
    name: "Lacttocol Max",
    slug: "lacttocol-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 441818, silver: 382909, gold: 343636, super_gold: 294545 },
    points: 130,
    image: "/images/products/lacttocol.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Lacttocol® Max - hỗ trợ đường ruột, tiêu hóa.",
    ingredients: "IMCDeltaImmune, Lactobacillus, Bifidobacterium, FOS (Fructo-oligosaccharide), chiết xuất nghệ, kẽm.",
    usage: "1-2 viên/lần, 2 lần/ngày. Trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ cân bằng hệ vi sinh đường ruột, tăng cường tiêu hóa, giảm rối loạn tiêu hóa.",
  },
  {
    id: 18,
    name: "Sữa tắm nữ",
    slug: "sua-tam-nu",
    category: "cham-soc-ca-nhan",
    prices: { normal: 352000, silver: 299000, gold: 255000, super_gold: 229000 },
    points: 100,
    image: "/images/products/sua-tam-nu.jpg",
    description: "Sữa tắm dành cho nữ, hương thơm nhẹ nhàng, dưỡng da mềm mịn.",
    ingredients: "Chiết xuất hoa hồng, Vitamin E, tinh dầu lavender, Glycerin, chiết xuất lô hội.",
    usage: "Lấy lượng vừa đủ, tạo bọt và massage nhẹ nhàng lên da, sau đó xả sạch.",
    benefits: "Làm sạch da dịu nhẹ, dưỡng ẩm, da mềm mịn, hương thơm quyến rũ.",
  },
  {
    id: 19,
    name: "Sữa tắm nam",
    slug: "sua-tam-nam",
    category: "cham-soc-ca-nhan",
    prices: { normal: 352000, silver: 299000, gold: 255000, super_gold: 229000 },
    points: 100,
    image: "/images/products/sua-tam-nam.jpg",
    description: "Sữa tắm dành cho nam, sảng khoái, năng động suốt ngày.",
    ingredients: "Than hoạt tính, tinh dầu bạc hà, Menthol, chiết xuất trà xanh, Glycerin.",
    usage: "Lấy lượng vừa đủ, tạo bọt và massage lên da, sau đó xả sạch.",
    benefits: "Làm sạch sâu, kiểm soát dầu thừa, sảng khoái, hương nam tính.",
  },
  {
    id: 20,
    name: "Green Quantum (Diệp lục)",
    slug: "green-quantum",
    category: "thuc-pham-bo-sung",
    prices: { normal: 192436, silver: 164945, gold: 133527, super_gold: 122727 },
    points: 54,
    image: "/images/products/diep-luc.jpg",
    description: "Green Quantum - Nước uống cô đặc diệp lục. Bổ sung chất xơ và diệp lục tố.",
    ingredients: "Chlorophyll (diệp lục tố), chiết xuất rau xanh, chất xơ hòa tan, Vitamin K, Magiê.",
    usage: "Pha 1 gói với 200ml nước, khuấy đều. Dùng 1-2 gói/ngày.",
    benefits: "Thanh lọc cơ thể, bổ sung chất xơ, hỗ trợ tiêu hóa, cung cấp diệp lục tố thiên nhiên.",
  },
  {
    id: 21,
    name: "Kidsmune Max",
    slug: "kidsmune-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 505636, silver: 451636, gold: 407455, super_gold: 378000 },
    points: 168,
    image: "/images/products/genecel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Kidsmune® Max - hỗ trợ miễn dịch cho trẻ em.",
    ingredients: "IMCDeltaImmune, Vitamin C, Kẽm, Vitamin D3, Beta-glucan, Lysine, chiết xuất thảo dược.",
    usage: "Trẻ em 2-6 tuổi: 1 viên/ngày. Trẻ em trên 6 tuổi: 1-2 viên/ngày. Nhai hoặc ngậm.",
    benefits: "Tăng cường miễn dịch cho trẻ, hỗ trợ phát triển, giảm nguy cơ ốm vặt.",
  },
  {
    id: 22,
    name: "Mindenergy Max",
    slug: "mindenergy-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 495818, silver: 446727, gold: 402545, super_gold: 373091 },
    points: 158,
    image: "/images/products/mindenergy.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Mindenergy® Max - hỗ trợ não bộ, tăng cường trí nhớ.",
    ingredients: "IMCDeltaImmune, Ginkgo Biloba, DHA, Phosphatidylserine, Vitamin B12, B6, acid Folic.",
    usage: "1-2 viên/lần, 2 lần/ngày. Trước ăn 30 phút hoặc sau ăn 1 giờ. Liên tục 3-6 tháng.",
    benefits: "Hỗ trợ tuần hoàn não, tăng cường trí nhớ và tập trung, giảm suy giảm trí nhớ.",
  },
  {
    id: 23,
    name: "Manlink Max",
    slug: "manlink-max",
    category: "bao-ve-suc-khoe",
    prices: { normal: 525818, silver: 463636, gold: 418545, super_gold: 354727 },
    points: 175,
    image: "/images/products/manlink.jpg",
    description: "Thực phẩm bảo vệ sức khỏe Man-Link® Max - hỗ trợ sức khỏe nam giới.",
    ingredients: "IMCDeltaImmune, Maca, Tongkat Ali, L-Arginine, Kẽm, Vitamin E, chiết xuất hàu.",
    usage: "2-4 viên/ngày, chia 2 lần. Trước ăn 30 phút hoặc sau ăn 1 giờ.",
    benefits: "Hỗ trợ tăng cường sinh lực nam giới, nâng cao sức khỏe phái mạnh.",
  },
  {
    id: 24,
    name: "Oricode Sâm",
    slug: "oricode-sam",
    category: "thuc-pham-bo-sung",
    prices: { normal: 625455, silver: 530182, gold: 451637, super_gold: 406473 },
    points: 175,
    image: "/images/products/bach-xuan.jpg",
    description: "Oricode Sâm - sản phẩm từ nhân sâm quý, bổ sung năng lượng và sức đề kháng.",
    ingredients: "Chiết xuất nhân sâm Hàn Quốc, mật ong, Royal Jelly, Vitamin nhóm B.",
    usage: "Dùng 1-2 gói/ngày. Pha với nước ấm hoặc uống trực tiếp.",
    benefits: "Bổ sung năng lượng, tăng sức đề kháng, chống mệt mỏi, nâng cao thể lực.",
  },
  {
    id: 25,
    name: "VTopcan",
    slug: "vtopcan",
    category: "bao-ve-suc-khoe",
    prices: { normal: 8826545, silver: 7658182, gold: 6872727, super_gold: 6185455 },
    points: 2850,
    image: "/images/products/vtopcan.jpg",
    description: "Thực phẩm bảo vệ sức khỏe VTopcan - gói 120 gói. Sản phẩm cao cấp nhất của Vinalink.",
    ingredients: "Tổng hợp các thành phần tinh túy từ tất cả sản phẩm TPBVSK của Vinalink, IMCDeltaImmune liều cao, phức hợp thảo dược quý.",
    usage: "Theo hướng dẫn chi tiết trên bao bì sản phẩm. Liên tục 3-6 tháng.",
    benefits: "Bảo vệ sức khỏe toàn diện, hỗ trợ miễn dịch mạnh mẽ, phù hợp cho người cần chăm sóc đặc biệt.",
  },
  {
    id: 26,
    name: "VSportGel",
    slug: "vsportgel",
    category: "bao-ve-suc-khoe",
    prices: { normal: 1914545, silver: 1659273, gold: 1497273, super_gold: 1364727 },
    points: 620,
    image: "/images/products/vsportgel.jpg",
    description: "Thực phẩm bảo vệ sức khỏe VSportGel - 50 gói. Hỗ trợ vận động viên và người tập thể thao.",
    ingredients: "Collagen peptide, Glucosamine, Chondroitin, MSM, Vitamin C, Kẽm, Magiê.",
    usage: "1-2 gói/ngày. Pha với nước hoặc uống trực tiếp, trước hoặc sau tập luyện.",
    benefits: "Hỗ trợ phục hồi cơ khớp, tăng cường sức bền, bảo vệ sụn khớp cho người vận động nhiều.",
  },
  {
    id: 27,
    name: "TOPAPRO (Bột Protein)",
    slug: "topapro",
    category: "thuc-pham-bo-sung",
    prices: { normal: 682364, silver: 603818, gold: 574364, super_gold: 540000 },
    points: 220,
    image: "/images/products/topapro.jpg",
    description: "Thực phẩm bổ sung TOPAPRO - Bột protein chất lượng cao.",
    ingredients: "Whey Protein Isolate, Protein đậu Hà Lan, BCAA, Glutamine, Vitamin nhóm B, khoáng chất.",
    usage: "Pha 1 gói với 200ml nước hoặc sữa, khuấy đều. Dùng 1-2 gói/ngày, trước hoặc sau tập luyện.",
    benefits: "Bổ sung protein chất lượng cao, hỗ trợ phát triển cơ bắp, phục hồi sau tập luyện.",
  },
  {
    id: 28,
    name: "Nước tẩy trang Orico Micellar Water",
    slug: "nuoc-tay-trang",
    category: "cham-soc-da",
    prices: { normal: 587127, silver: 489927, gold: 440836, super_gold: 397636 },
    points: 185,
    image: "/images/products/nuoc-tay-trang.jpg",
    description: "Nước tẩy trang Orico Micellar Water - làm sạch sâu, dịu nhẹ cho da.",
    ingredients: "Micellar Water, chiết xuất hoa hồng, Vitamin B5, Glycerin, Allantoin.",
    usage: "Thấm nước tẩy trang lên bông cotton, lau nhẹ nhàng lên mặt cho đến khi sạch.",
    benefits: "Làm sạch makeup hiệu quả, không gây khô da, dưỡng ẩm nhẹ, phù hợp da nhạy cảm.",
  },
  {
    id: 29,
    name: "Nước hoa hồng Orico Toner",
    slug: "nuoc-hoa-hong-toner",
    category: "cham-soc-da",
    prices: { normal: 540000, silver: 451636, gold: 407455, super_gold: 368182 },
    points: 170,
    image: "/images/products/toner.jpg",
    description: "Nước hoa hồng Orico Toner - cân bằng da, se khít lỗ chân lông.",
    ingredients: "Chiết xuất hoa hồng Damask, Hyaluronic Acid, Niacinamide, Witch Hazel, Panthenol.",
    usage: "Sau khi rửa mặt, thấm toner lên bông cotton hoặc tay, vỗ nhẹ lên da.",
    benefits: "Cân bằng pH da, se khít lỗ chân lông, cấp ẩm, chuẩn bị da cho các bước dưỡng tiếp theo.",
  },
  {
    id: 30,
    name: "Sữa rửa mặt Orico Cleanser",
    slug: "sua-rua-mat",
    category: "cham-soc-da",
    prices: { normal: 378000, silver: 314182, gold: 284727, super_gold: 255273 },
    points: 115,
    image: "/images/products/sua-rua-mat.jpg",
    description: "Sữa rửa mặt Orico Cleanser - làm sạch da dịu nhẹ hàng ngày.",
    ingredients: "Amino Acid surfactant, chiết xuất trà xanh, Centella Asiatica, Vitamin B5, Aloe Vera.",
    usage: "Lấy lượng vừa đủ, tạo bọt với nước, massage nhẹ nhàng lên mặt 1 phút rồi rửa sạch.",
    benefits: "Làm sạch sâu nhưng dịu nhẹ, không khô căng, kiểm soát dầu, phù hợp mọi loại da.",
  },
  {
    id: 31,
    name: "Kem chống nắng Orico Sun Screen",
    slug: "kem-chong-nang",
    category: "cham-soc-da",
    prices: { normal: 711818, silver: 561600, gold: 505636, super_gold: 456545 },
    points: 210,
    image: "/images/products/kem-chong-nang.jpg",
    description: "Kem chống nắng Orico Sun Screen - bảo vệ da khỏi tia UV.",
    ingredients: "Zinc Oxide, Titanium Dioxide, Niacinamide, Vitamin E, Hyaluronic Acid, chiết xuất rau má.",
    usage: "Thoa đều lên da mặt và vùng da tiếp xúc ánh nắng trước 15-20 phút. Thoa lại mỗi 2-3 giờ.",
    benefits: "Bảo vệ da khỏi tia UVA/UVB, ngăn ngừa lão hóa do nắng, dưỡng ẩm, không bết dính.",
  },
  {
    id: 32,
    name: "Kem dưỡng da Orico Cream",
    slug: "kem-duong-da",
    category: "cham-soc-da",
    prices: { normal: 1030909, silver: 890000, gold: 810000, super_gold: 730000 },
    points: 300,
    image: "/images/products/kem-duong.jpg",
    description: "Kem dưỡng da Orico Cream - dưỡng ẩm sâu, chống lão hóa.",
    ingredients: "Retinol, Hyaluronic Acid, Peptide Complex, Vitamin C, Squalane, Ceramide, chiết xuất nhau thai cừu.",
    usage: "Thoa đều lên da mặt và cổ sau bước toner và serum. Dùng sáng và tối.",
    benefits: "Dưỡng ẩm sâu, chống lão hóa, làm sáng da, cải thiện nếp nhăn, da căng mịn.",
  },
];

export function formatPrice(price: number): string {
  return price.toLocaleString("vi-VN");
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
